# Generated by Django 5.1 on 2024-08-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'managed': True},
        ),
    ]
